### PR TITLE
update to 0.45 and swift 5.4

### PR DESCRIPTION
**Pull request by KarimAlweheshy**

### CODE REVIEW

**Comment by fede-moya** [comment]
@KarimAlweheshy hey 👋🏼  - sorry the delay here. Could you point your base to [swiftlint-0.45](https://github.com/codeclimate/codeclimate-swiftlint/tree/swiftlint-0.45)

**Review by fede-moya — COMMENTED** [review]
waiting for base branch to be changed

**Comment by KarimAlweheshy** [comment]
@fede-moya ✅

**Comment by fede-moya** [comment]
@KarimAlweheshy Great, merging !! Thank you for your contribution.

**Pull request merged**
